# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-07-02 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skladnik',
            options={'verbose_name_plural': 'skladniki'},
        ),
    ]
